//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraylogArduinoTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int QueryInterval_ms {
            get {
                return ((int)(this["QueryInterval_ms"]));
            }
            set {
                this["QueryInterval_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBalloon {
            get {
                return ((bool)(this["ShowBalloon"]));
            }
            set {
                this["ShowBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.120.156:9200/_search")]
        public string ProdErrorURI {
            get {
                return ((string)(this["ProdErrorURI"]));
            }
            set {
                this["ProdErrorURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{   
""query"" : {
        ""filtered"": {
            ""filter"": {
                ""bool"": {
                    ""must"": [{
                        ""range"": {
                            ""timestamp"": {
                                ""gte"": ""now/d""
                            }
                        }
                    },
                    {
                        ""term"": {
                            ""streams"": ""56137f99e4b0d01f53360fa2""
                        }
                    }]
                }
            }
        }
    },
    ""sort"": [
    {""timestamp"" : {""order"":""desc"", ""unmapped_type"" : ""long""}}]
}")]
        public string ProdErrorJSON {
            get {
                return ((string)(this["ProdErrorJSON"]));
            }
            set {
                this["ProdErrorJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"http://192.168.120.155:5601/#/dashboard/System-Health?_g=(refreshInterval:(display:'10%20seconds',pause:!f,section:1,value:10000),time:(from:now-4h,mode:quick,to:now))&_a=(filters:!(),panels:!((col:1,columns:!(message,Severity,source,SourceName,Category),id:Errors-Production,row:1,size_x:12,size_y:4,sort:!(timestamp,desc),type:search),(col:1,columns:!(message,Severity,source,SourceName,Category),id:Warnings-Production,row:5,size_x:12,size_y:4,sort:!(timestamp,desc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'System%20Health')")]
        public string OnTrayBalloonClickURI {
            get {
                return ((string)(this["OnTrayBalloonClickURI"]));
            }
            set {
                this["OnTrayBalloonClickURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLogging {
            get {
                return ((bool)(this["EnableLogging"]));
            }
            set {
                this["EnableLogging"] = value;
            }
        }
    }
}
