//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraylogArduinoTray.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int QueryInterval_ms {
            get {
                return ((int)(this["QueryInterval_ms"]));
            }
            set {
                this["QueryInterval_ms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBalloon {
            get {
                return ((bool)(this["ShowBalloon"]));
            }
            set {
                this["ShowBalloon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.120.156:9200/_search")]
        public string ProdErrorURI {
            get {
                return ((string)(this["ProdErrorURI"]));
            }
            set {
                this["ProdErrorURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{   
""query"" : {
        ""filtered"": {
            ""filter"": {
                ""bool"": {
                    ""must"": [{
                        ""range"": {
                            ""timestamp"": {
                                ""gte"": ""now/d""
                            }
                        }
                    },
                    {
                        ""term"": {
                            ""streams"": ""56137f99e4b0d01f53360fa2""
                        }
                    }]
                }
            }
        }
    },
    ""sort"": [
    {""timestamp"" : {""order"":""desc"", ""unmapped_type"" : ""long""}}]
}")]
        public string ProdErrorJSON {
            get {
                return ((string)(this["ProdErrorJSON"]));
            }
            set {
                this["ProdErrorJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string OnTrayBalloonClickURI {
            get {
                return ((string)(this["OnTrayBalloonClickURI"]));
            }
            set {
                this["OnTrayBalloonClickURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLogging {
            get {
                return ((bool)(this["EnableLogging"]));
            }
            set {
                this["EnableLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BalloonTime_s {
            get {
                return ((int)(this["BalloonTime_s"]));
            }
            set {
                this["BalloonTime_s"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Newlines_in_Balloon {
            get {
                return ((int)(this["Newlines_in_Balloon"]));
            }
            set {
                this["Newlines_in_Balloon"] = value;
            }
        }
    }
}
